apiVersion: v1
kind: ConfigMap
metadata:
  name: env-bran
data:
  SECRET_KEY: "django-insecure-8j=hrs#^z0t%#1^89isbgqeddf2_zw!#zh45rz-=h&u%ze)o3e"
  ALLOWED_HOSTS: "*"
  DEBUG: "true"
  TIME_ZONE: "UTC"
